id: P9747BB24
initial_creation_type: input
source_metadata:
  title: Buddhist Philosophy Series
  language: it
  description: 'The following texts are available as part of our Buddhist Philosophy
    series:'
  volume:
    f6fb0d7876c04ca28ed43851eea549ea:
      title: Synopsis of the Treasury of Abhidharma (Abhidharmakośa)
      parent: Abhidharma
    504fe521b6f2434c8f40a23ca59094b4:
      title: Brief Analysis of the Five Aggregates
      parent: Abhidharma
    948109a4a5f042fbb905f74e8fadebe6:
      title: A Brief Explanation of the Ten Virtues and Eighteen Elements
      parent: Abhidharma
    0526fc332590458fbdb07618c5272a32:
      title: Putting the Instruction on the Purification of Mental Activity into Practice
      parent: Analytical Meditation
    8982fd160236444f9f5ee63feb35be40:
      title: The Wheel of Analytical Meditation That Thoroughly Purifies Mental Activity
      parent: Analytical Meditation
    6a8b7f0a40194cf5a349d5f62e2f926c:
      title: A Song for Travelling from Sikkim to Tibet
      parent: Buddha Nature
    926f40be9966442491c9462b9f26d085:
      title: On the Yogācāra Treatises and Buddha Nature
      parent: Buddha Nature
    f67fbd5311544c488a7f9c92240c3807:
      title: A Brief Presentation of the Nine Vehicles
      parent: Categories of Teaching
    9e8e7cf07c064defaba79a7bf5371774:
      title: A Brief Overview of the Three Turnings and the Mantra Piṭaka of the Vidyādharas
      parent: Categories of Teaching
    eca288bbf70947208e8f7b1824f1ab5c:
      title: Commentary on Nāgārjuna's Verses on the Essence of Dependent Origination
      parent: Dependent Origination
    6e106822bad94fd0ad60c07f9cbfbe3a:
      title: Commentary on the Noble Essence of the Dharmadhātu
      parent: Dependent Origination
    9fc516761a03468cad170f865cee7ed5:
      title: Verses on the Heart of Dependent Origination
      parent: Dependent Origination
    bcac2c154336447a8f2e6a0f9e82b9b5:
      title: On Knowable Objects
      parent: Logic and Epistemology
    af4e32e0620e49bca9f904368e940789:
      title: The Sword of Wisdom for Thoroughly Ascertaining Reality
      parent: Logic and Epistemology
    46b2556b9ca140ddbe50c3a3087237b0:
      title: Conveying the Essence of the Middle Way of Consequence
      parent: Middle Way
    b31fbf0765b14f6cb5877bb74b61979e:
      title: 'The Words of Candra: The Definitive Secret of the Great Middle Way of
        Consequence Beyond Extremes, the Fundamental Intent of All the Tathāgatas'
      parent: Middle Way
    be6d67f946814c11902db52470bf3dd4:
      title: 'The Seed of Reasoning: Notes on the Five Great Logical Arguments of
        the Middle Way'
      parent: Middle Way
    77cf3d33553648608380c7a3b6e9a253:
      title: 'Gateway to Learning: Four Great Logical Arguments of the Middle Way'
      parent: Middle Way
    0b69ba0706bd4ce9ac38d22a7fb828c5:
      title: Notes from Miscellaneous Writings
      parent: Pedagogy
    33d477d1eda44754a7af5a3a26537443:
      title: Preliminary Points to be Explained When Teaching the Buddha's Word or
        the Treatises
      parent: Pedagogy
    e46a5cff273a4d469523eacf39703f5f:
      title: 'The Vajra Mirror: Cutting through Doubts Concerning Self-Awareness'
      parent: Self-Awareness
    167fa393a131486b854f290e47a6d8e8:
      title: Ascertaining the Two Kinds of Selflessness
      parent: Selflessness
    2c565d9aae154d3aa17412c26e067690:
      title: 'Gateway to Learning: Individual Selflessness'
      parent: Selflessness
    d9bf012f5229490aa320ab139b2ffbd2:
      title: A Brief Guide to the Stages and Paths of the Bodhisattvas
      parent: Stages and Paths
    aa7510acc71642f8a563c5a7e6bc2e21:
      title: 'Elucidating the Hidden Meaning: A Commentary on the Meaning of the Four
        Mudrās'
      parent: Tantra
    fd4a9f7ae4f84f6fa1dfa231daf8aac3:
      title: Seeds of the Four Philosophical Schools
      parent: Tenets
    7367c6f680e74323a364bfd85781529c:
      title: 'The Concentrated Seed: How to Distinguish the Tenets of Non-Buddhist
        and Buddhist Schools'
      parent: Tenets
    69d791863fa648d583a58c43048c03f8:
      title: The Black Snake Discourse
      parent: Tenets
    e6f9f9f1cbdf4ead8643cdb01defce8e:
      title: Elucidating the Essence of the Instructions for Entering the Three Gateways
        to Liberation
      parent: Three Gateways to Liberation
    006f09382e2940f0832bc251addeabb7:
      title: 'The Excellent Path of the Great Vehicle: How to Meditate on the Three
        Gateways to Liberation According to the Mahāyāna'
      parent: Three Gateways to Liberation
    31b1cdb636704ca28fafb7c8e49fdc4d:
      title: An Instruction on the View of the Mahāyāna – Clarifying the Two Truths
      parent: Two Truths
created_at: '2022-03-01T03:08:46.916730'
last_modified_at: '2022-03-01T03:08:46.916733'
